#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: android-open-rw <file>" >&2
    exit 2
fi

FILE="$1"

exec /data/data/com.termux/files/usr/bin/termux-open \
    --content-type application/vnd.remotevault.openrw \
    "$FILE"
